.TH "CINELERRA" "1" 
.SH "NAME" 
cinelerra \(em A non-linear audio & video authoring tool 
.SH "SYNOPSIS" 
.PP 
\fBcinelerra\fR [\fB-h\fI\fR\fP]  [\fB-p\fIport\fR\fP]  
.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the 
\fBcinelerra\fR command. 
.PP 
\fBcinelerra\fR is a non-linear audio & video authoring tool. 
 
.SH "OPTIONS" 
.IP "\fB-h\fP" 10 
Shows available command line options. 
.IP "\fB-p [port]\fP" 10 
Runs in the background as renderfarm client. 
Port is the port for client to listen on (default: 400) 
.SH "AUTHOR" 
.PP 
This manual page was written by Sylvain Joyeux <sylvain.joyeux@m4x.org> for 
the \fBDebian GNU/Linux\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU Free Documentation 
License, Version 1.1 or any later version published by the Free 
Software Foundation; with no Invariant Sections, no Front-Cover 
Texts and no Back-Cover Texts. 
.\" created by instant / docbook-to-man, Mon 27 Aug 2007, 16:56 
