.TH "CINELERRA" "1" 
.SH "NAME" 
mplexlo \(em A tiny MPEG1 multiplexer 
.SH "SYNOPSIS" 
.PP 
\fBmplexlo\fR [\fB-a\fI\fR\fP]  [\fBstream1\fP]  [\fBstream2\fP]  [\fB...\fP]  [\fBstreamN\fP]  [\fBoutput\fP]  
.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the 
\fBmplexlo\fR command. 
.PP 
\fBmplexlo\fR is a tiny MPEG1 multiplexer 
 
.SH "OPTIONS" 
.IP "\fB-a\fP" 10 
Use AC3 headers. 
.SH "AUTHOR" 
.PP 
This manual page was written by Sylvain Joyeux <sylvain.joyeux@m4x.org> for 
the \fBDebian GNU/Linux\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU Free Documentation 
License, Version 1.1 or any later version published by the Free 
Software Foundation; with no Invariant Sections, no Front-Cover 
Texts and no Back-Cover Texts. 
.\" created by instant / docbook-to-man, Mon 27 Aug 2007, 16:57 
